name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
          components: rustfmt, clippy
      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
